# Generated by Django 5.2.3 on 2025-07-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scayflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='tarifa_monto',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='utilidad_total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
