# Generated by Django 5.2.3 on 2025-07-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scayflow', '0002_alter_cliente_rfc_alter_cliente_telefono_proyecto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='responsable_dependecnia',
            new_name='responsable_dependencia',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tarifa_monto',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='fecha_ultima_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
