# Generated by Django 5.2.3 on 2025-07-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scayflow', '0003_rename_responsable_dependecnia_tramite_responsable_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='duracion_estimada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='tiempo_resolucion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='total_tramite',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
